### PR TITLE
Bump csh-material-bootstrap to 4.3.1

### PR DESCRIPTION
**Pull request by RamZallan**

### CODE REVIEW

**Comment by mxmeinhold** [comment]
Are these the only two that are updated?

**Comment by RamZallan** [comment]
@mxmeinhold, Seems like it, although I see commits bringing them up to bootstrap 4.3.1, https://assets.csh.rit.edu/csh-datto-bootstrap/4.3.1/dist/csh-datto-bootstrap.min.css and https://assets.csh.rit.edu/csh-pastel-bootstrap/4.3.1/dist/csh-pastel-bootstrap.min.css both 404 for me.

**Comment by mxmeinhold** [comment]
Oh, I think the CI pipeline failed. Want me to merge this now or try and fix it first?

**Comment by RamZallan** [comment]
I'm fine to wait a bit on this getting merged if you want to bump all the versions. LMK if you get them working and I/you can add a commit to this PR

**Pull request merged**
